CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE "Roles" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" uuid NOT NULL,
    "Username" text NOT NULL,
    "PasswordHash" bytea NOT NULL,
    "PasswordHashingKey" bytea NOT NULL,
    "RoleId" integer NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE SET NULL
);

INSERT INTO "Roles" ("Id", "Name")
VALUES (1, 'Admin');
INSERT INTO "Roles" ("Id", "Name")
VALUES (2, 'User');
INSERT INTO "Roles" ("Id", "Name")
VALUES (3, 'Bot');

CREATE UNIQUE INDEX "IX_Roles_Id" ON "Roles" ("Id");

CREATE UNIQUE INDEX "IX_Roles_Name" ON "Roles" ("Name");

CREATE UNIQUE INDEX "IX_Users_Id" ON "Users" ("Id");

CREATE INDEX "IX_Users_RoleId" ON "Users" ("RoleId");

CREATE UNIQUE INDEX "IX_Users_Username" ON "Users" ("Username");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20201031134017_initial', '3.1.9');

ALTER TABLE "Users" ADD "IsDeleted" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20201110174609_Added isDeleted property', '3.1.9');

