name: CI script

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '5.0.x' ]
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install dependencies
      run: dotnet restore ./src/
    - name: Build
      run: dotnet build ./src/ --configuration Release --no-restore
    - name: Test
      run: dotnet test ./src/ --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"
